import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/context/rootProvider";
import { SocketProvider } from "@/context/helper/socket";
import { AxiosProvider } from "@/context/helper/axios";

export const metadata: Metadata = {
  title: "Nexync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-bg_main text-font_main w-screen h-screen`}
      >
        <ReduxProvider>
          <SocketProvider>
            <AxiosProvider>{children}</AxiosProvider>
          </SocketProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
