import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/context/rootProvider";

export const metadata: Metadata = {
  title: "Nexync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-bg_main text-font_main w-screen h-screen`}
      >
        <ReduxProvider>
        {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
